#auth 서비스 설정
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 133aa3a6e799cfd6b374149ef9d943e2
            client-secret: mtkht02IAB7XUV4cafDeGrPLiwHxqg9X
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/apis/oauth/kakao/redirect
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

